spring:
  application:
    name: zerobase-financial

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:zerobase;DB_CLOSE_DELAY=-1
    username: sa
    password: zerobase

  redis:
    host: localhost
    port: 6379
#    password: zerobase

  jwt:
    secret: aGFrc3V5b29uLXN0dWR5LWRpdmlkZW50LXByb2plY3Qtc3ByaW5nLWJvb3Qtand0LXNlY3JldC1rZXktd2h5LWl0LWRvZXNudC1zb2x2ZS1wcm9ibGVtLWF1dGgtYW5ncnktYW5ncnkK


scheduler:
  scrap:
    yahoo: "0 0 0 * * *"

logging:
  config: classpath:logback-spring.xml